includes:
  - base.yaml
targets:
  - target: /bin
    createlinks:
      - src: /opt/python-occlum/bin/python3
        linkname: python3
  # python packages
  - target: /opt
    copy: 
      - dirs:
          - /python-occlum
  # below are python code and data
  - target: /bin
    copy:
      - dirs:
          - /sentra

  #Attester and run script
  - target: /bin
    copy:
     - files:
        - /attester/target/release/sentra_attester
        - /enclave_run_script.sh

# Shell
  - target: /bin
    copy:
     - files:
        - /opt/occlum/toolchains/bash/glibc/bash
        - /opt/occlum/toolchains/busybox/glibc/busybox

#Pebble TLS root CA cert
  - target: /etc
    copy:
     - files:
        - /attester/pebble.cer

 # copy lib
#  - target: /opt/occlum/glibc/lib
#    copy:
 #     - files:
 #       - /opt/occlum/toolchains/dcap_lib/glibc/libocclum_dcap.so.0.1.0
