apiVersion: v1
kind: Namespace
metadata:
  name: sentra
  annotations:
    description: "Namespace for Sentra"
---
apiVersion: v1
kind: Service
metadata:
  name: sentra-backend
  namespace: sentra
  labels:
    app: sentra-backend
spec:
  selector:
    app: sentra-backend
    role: backend
  ports:
   - name: webgui
     protocol: TCP
     port: 8888
   - name: grpc
     protocol: TCP
     port: 8000
   - name: secure-grpc
     protocol: TCP
     port: 8001
   - name: acme-service
     protocol: TCP
     port: 14000
   - name: acme-management
     protocol: TCP
     port: 15000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentra-ingress
  namespace: sentra
spec:
  ingressClassName: nginx
  rules:
  - http:  # No host specified
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sentra-backend
            port:
              number: 8888
---
apiVersion: v1
kind: Pod
metadata:
  name: sentra-backend
  namespace: sentra
  labels:
    app: sentra-backend
    role: backend
spec:
  containers:
  - name: sentra-backend
    image: registry.tdp.trustworthy6g.net/tdp/sentra/sentra-backend:latest
    imagePullPolicy: Always
    args: ["--use-acme","--acme-host","127.0.0.1","--acme-server-certificate","/pebble/pebble.cer"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentra-node
  namespace: sentra
  labels:
    app: sentra-node
spec:
  replicas: 8
  selector:
    matchLabels:
      app: sentra-node
  template:
    metadata:
      name: sentra-node
      namespace: sentra
      labels:
        app: sentra-node
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: sentra-node
      containers:
      - name: sentra-node
        image: registry.tdp.trustworthy6g.net/tdp/sentra/sentra-sgx:latest
        imagePullPolicy: Always
        args: ["--grpc-url", "https://sentra-backend:8001","--use-acme","--acme-url","https://sentra-backend:14000","--acme-cert","/etc/pebble.cer"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: sgx-enclave
          mountPath: /dev/sgx_enclave
        - name: sgx-provision
          mountPath: /dev/sgx_provision
      volumes:
        - name: sgx-enclave
          hostPath:
            path: /dev/sgx_enclave
            type: CharDevice
        - name: sgx-provision
          hostPath:
            path: /dev/sgx_provision
            type: CharDevice
