[package]
name = "Sentra-Attester"
version = "0.1.0"
edition = "2021"

[dependencies]
occlum-sgx = "0.1.13"
axum = "=0.7.0"
tokio = { version = "=1.47.1", features = ["full"] }
indexmap="=2.11.0"
syn = "=2.0.106"
log="=0.4.28"

[[bin]]
name = "sentra_attester"
path ="src/main.rs"

#[patch.crates-io]
#syn = { version = "=2.0.106" }
#log="=0.4.28"
