syntax = "proto3";

package sentra_backend_grpc_services;

service NodeMessageService {
rpc NodeStream (stream NodeMessage) returns (stream ServerMessage);
}

message RegisterRequest {
    string node_id = 1;
}

message RegisterResponse {
    bool success = 1;
    string message = 2;
}

message AttestationRequest {
    string nonce = 1;
}

message AttestationResponse {
    bytes report = 1;
}

// Message from node to server (client -> server)
message NodeMessage {
    oneof message_type {
        RegisterRequest register = 1;
        AttestationResponse quote=2;
    }
}

// Message from server to node (server -> client)
message ServerMessage {
    oneof message_type {
        RegisterResponse response = 1;
        AttestationRequest attestation=2;
    }
}
