name: sentra

x-sentra-core: &x-sentra-core
    build:
      context: ../
      dockerfile: ./sgx/SentraSGX.dockerfile
    image: sentra-sgx
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"


services:

  sentra-simple-training:
    <<: *x-sentra-core
    command: /bin/sentra/run_training.py
    container_name: sentra-test
    deploy:
      mode: replicated-job
      replicas: 1
    profiles:
      - test

  sentra-dp-training:
    <<: *x-sentra-core
    command: /bin/sentra/run_dp_training.py
    container_name: sentra-dp-test
    deploy:
      mode: replicated-job
      replicas: 1
    profiles:
      - dp-test



