name: sentra

x-sentra-core: &x-sentra-core
    build:
      context: ../
      dockerfile: ./sgx/SentraSGX.dockerfile
    image: sentra-sgx
    deploy:
      mode: replicated-job
      replicas: 1
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"

x-sentra-multi-node: &x-sentra-multi-node
  <<: *x-sentra-core
  profiles:
      - multi-node

x-sentra-verifier: &x-sentra-verifier
  build:
    context: ../
    dockerfile: ./attestation/verifier/Dockerfile
  image: sentra-verifier 
  deploy:
    mode: replicated-job
    replicas: 1
  devices:
    - "/dev/sgx_enclave:/dev/sgx_enclave"
    - "/dev/sgx_provision:/dev/sgx_provision"

services:
  sentra-simple-training:
    <<: *x-sentra-core
    command: /bin/sentra/run_training.py
    container_name: sentra-test
    profiles:
      - test

  sentra-dp-training:
    <<: *x-sentra-core
    command: /bin/sentra/run_dp_training.py
    container_name: sentra-dp-test
    profiles:
      - dp-test

  sentra-node-1:
    <<: *x-sentra-multi-node
    command: /bin/sentra/run_node.py --config /bin/sentra/node_config.yaml --auto-close --node-id 1

  sentra-node-2:
    <<: *x-sentra-multi-node
    command: /bin/sentra/run_node.py --config /bin/sentra/node_config.yaml --auto-close --node-id 2

  sentra-node-3:
    <<: *x-sentra-multi-node
    command: /bin/sentra/run_node.py --config /bin/sentra/node_config.yaml --auto-close --node-id 3

  sentra-node-4:
    <<: *x-sentra-multi-node
    command: /bin/sentra/run_node.py --config /bin/sentra/node_config.yaml --auto-close --node-id 4
 
  sentra-node-5:
    <<: *x-sentra-multi-node
    command: /bin/sentra/run_node.py --config /bin/sentra/node_config.yaml --auto-close --node-id 5

  sentra-verifier:
    <<: *x-sentra-verifier
    command: /bin/attestation/verifier
    profiles:
      - test