1:
  host: sentra-node-1
  port: 8080
2:
  host: sentra-node-2
  port: 8080
3:
  host: sentra-node-3
  port: 8080
4:
  host: sentra-node-4
  port: 8080
5:
  host: sentra-node-5
  port: 8080
