# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SentraBackend-GRPC-Services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SentraBackend-GRPC-Services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!SentraBackend-GRPC-Services.proto\x12\x1csentra_backend_grpc_services\"\"\n\x0fRegisterRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\x10NodeRegistration\x12m\n\x0cRegisterNode\x12-.sentra_backend_grpc_services.RegisterRequest\x1a..sentra_backend_grpc_services.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SentraBackend_GRPC_Services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=67
  _globals['_REGISTERREQUEST']._serialized_end=101
  _globals['_REGISTERRESPONSE']._serialized_start=103
  _globals['_REGISTERRESPONSE']._serialized_end=155
  _globals['_NODEREGISTRATION']._serialized_start=158
  _globals['_NODEREGISTRATION']._serialized_end=287
# @@protoc_insertion_point(module_scope)
