# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import SentraBackend_GRPC_Services_pb2 as SentraBackend__GRPC__Services__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in SentraBackend_GRPC_Services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeMessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NodeStream = channel.stream_stream(
                '/sentra_backend_grpc_services.NodeMessageService/NodeStream',
                request_serializer=SentraBackend__GRPC__Services__pb2.NodeMessage.SerializeToString,
                response_deserializer=SentraBackend__GRPC__Services__pb2.ServerMessage.FromString,
                _registered_method=True)


class NodeMessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NodeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NodeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.NodeStream,
                    request_deserializer=SentraBackend__GRPC__Services__pb2.NodeMessage.FromString,
                    response_serializer=SentraBackend__GRPC__Services__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentra_backend_grpc_services.NodeMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentra_backend_grpc_services.NodeMessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeMessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NodeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sentra_backend_grpc_services.NodeMessageService/NodeStream',
            SentraBackend__GRPC__Services__pb2.NodeMessage.SerializeToString,
            SentraBackend__GRPC__Services__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
